-- 카트에 상품 추가
INSERT INTO CART (cID, mID, pID, cAMOUNT)
    VALUES (CART_SEQ.NEXTVAL, 'aaa', '1', 1);
INSERT INTO CART (cID, mID, pID, cAMOUNT)
    VALUES (CART_SEQ.NEXTVAL, 'aaa', '2', 1);
INSERT INTO CART (cID, mID, pID, cAMOUNT)
    VALUES (CART_SEQ.NEXTVAL, 'aaa', '3', 1);

-- 카트에 넣은 상품 정보 수정(수량만 변경 가능)
UPDATE CART SET cAMOUNT = 3 WHERE cId='5';

-- 카트에 넣은 상품 빼기(삭제)
DELETE CART WHERE cId='1';

-- 카트에 있는 상품 리스트 보기(startRow, endRow)
SELECT C.*, pIMAGE1, pNAME, pPRICE, pPRICE*cAMOUNT cTOTSUM FROM CART C, PRODUCT P WHERE mID='aaa202' AND C.pID=P.pID ORDER BY cDATE DESC;
SELECT*FROM (SELECT ROWNUM RN, A.* FROM 
    (SELECT C.*, pIMAGE1, pNAME, pPRICE, pPRICE*cAMOUNT cTOTSUM FROM CART C, PRODUCT P WHERE mID=? AND C.pID=P.pID ORDER BY cDATE DESC)A)
    WHERE RN BETWEEN 1 AND 3;

-- 카트 전체 상품 개수
SELECT COUNT(*) TOTCNT FROM CART WHERE mID='aaa202'; 

-- mID로 카트 Dto 가져오기
SELECT*FROM CART WHERE mID='bbarkji';

commit;

SELECT C.*, pIMAGE1, pNAME, pPRICE, pPRICE*cAMOUNT cTOTSUM FROM CART C, PRODUCT P WHERE cID=5 AND C.pID=P.pID ORDER BY cDATE DESC;
SELECT ORDERS_SEQ.CURRVAL oID FROM DUAL;
SELECT O.OID, ODATE, ONAME, PID, ODAMOUNT, (SELECT ODAMOUNT*PPRICE FROM PRODUCT P, ORDERS_DETAIL OD WHERE P.PID=OD.PID) FROM ORDERS O, ORDERS_DETAIL OD WHERE O.OID=OD.OID AND O.OID=1;