-- 오더 디테일 추가
INSERT INTO ORDERS_DETAIL(odID, oID, pID, odAMOUNT) VALUES (ORDERS_DETAIL_SEQ.nextval, ORDERS_SEQ.CURRVAL, '1', 3);

-- oID로 odID dto 불러오기
SELECT OD.*, pIMAGE1, pNAME, pPRICE, pPRICE*odAMOUNT ODTOTSUM FROM ORDERS_DETAIL OD, PRODUCT P WHERE OD.pID=P.pID AND oID='1';
SELECT oDATE, OD.*, pIMAGE1, pNAME, pPRICE, pPRICE*odAMOUNT ODTOTSUM FROM ORDERS O, ORDERS_DETAIL OD, PRODUCT P WHERE O.OID=OD.OID AND OD.pID=P.pID AND od.oID='10';


전체 오더리스트
SELECT*FROM (SELECT ROWNUM RN, A.* FROM (SELECT OD.*, pIMAGE1, pNAME, pPRICE, pPRICE*odAMOUNT ODTOTSUM FROM ORDERS_DETAIL OD, PRODUCT P WHERE OD.pID=P.pID)A) WHERE RN BETWEEN 2 AND 4;

-- 전체 오더리스트 - oid로 조회
SELECT*FROM (SELECT ROWNUM RN, A.* FROM (SELECT OD.*, pIMAGE1, pNAME, pPRICE, pPRICE*odAMOUNT ODTOTSUM FROM ORDERS_DETAIL OD, PRODUCT P WHERE OD.pID=P.pID AND oID='1')A) WHERE RN BETWEEN 2 AND 4;


-- 특정 회원 주문 상세 보기
SELECT O.*, OD.* FROM ORDERS O, ORDERS_DETAIL OD WHERE O.oID=OD.oID AND mID='aaa' AND O.oID='1';

SELECT*FROM ORDERS_DETAIL;

-- mId 로 odId dto 전체 불러오기
SELECT oDATE, OD.*, pIMAGE1, pNAME, pPRICE, pPRICE*odAMOUNT ODTOTSUM FROM ORDERS O, ORDERS_DETAIL OD, PRODUCT P WHERE O.OID=OD.OID AND OD.pID=P.pID AND mID='bbarkji' ORDER BY O.OID DESC;

-- mId로 전체 개수
SELECT COUNT(*) TOTCNT FROM ORDERS O, ORDERS_DETAIL OD, PRODUCT P WHERE O.OID=OD.OID AND OD.pID=P.pID AND mID='bbarkji';

-- 전체 오더 디테일 리스트 - mID로 조회
SELECT*FROM (SELECT ROWNUM RN, A.* FROM 
    (SELECT oDATE, OD.*, pIMAGE1, pNAME, pPRICE, pPRICE*odAMOUNT ODTOTSUM FROM 
        ORDERS O, ORDERS_DETAIL OD, PRODUCT P WHERE O.OID=OD.OID AND OD.pID=P.pID AND mID='bbarkji' 
            ORDER BY O.OID DESC)A) WHERE RN BETWEEN 2 AND 4;
            
COMMIT;