DROP TABLE MEMBER;
DROP TABLE ADMIN;

DROP TABLE pCATEGORY;
DROP TABLE PRODUCT CASCADE CONSTRAINTS;
DROP SEQUENCE PRODUCT_SEQ;

DROP TABLE WISHLIST;
DROP SEQUENCE WISHLIST_SEQ;

DROP TABLE QNA_BOARD;
DROP SEQUENCE QNA_SEQ;

DROP TABLE REVIEW_BOARD;
DROP SEQUENCE REVIEW_SEQ;

DROP TABLE CART;
DROP SEQUENCE CART_SEQ;

DROP TABLE ORDERS CASCADE CONSTRAINTS;
DROP SEQUENCE ORDERS_SEQ;

DROP TABLE ORDERS_DETAIL;
DROP SEQUENCE ORDERS_DETAIL_SEQ;

CREATE TABLE MEMBER(
    mID VARCHAR2(50) PRIMARY KEY,
    mPW VARCHAR2(50) NOT NULL,
    mNAME VARCHAR2(50) NOT NULL,
    mEMAIL VARCHAR2(250) NOT NULL,
    mPHONE VARCHAR2(50) NOT NULL,
    mADDRESS VARCHAR2(350) NOT NULL,
    mBIRTH DATE,
    mDATE DATE DEFAULT SYSDATE,
    mDROP NUMBER(1) DEFAULT 0
);

CREATE TABLE ADMIN(
    aID VARCHAR2(50) PRIMARY KEY,
    aPW VARCHAR2(50) NOT NULL,
    aNAME VARCHAR2(50) 
);

CREATE TABLE PRODUCT(
    pID NUMBER(7) PRIMARY KEY,
    pCATEGORY VARCHAR2(50) NOT NULL,
    pNAME VARCHAR2(50) NOT NULL, 
    pPRICE NUMBER(7) NOT NULL,
    pDISCOUNT NUMBER(3) DEFAULT 0,
    pIMAGE1 VARCHAR2(250) NOT NULL,
    pIMAGE2 VARCHAR2(250),
    pCONTENT VARCHAR2(4000),
    pPOLICY1 VARCHAR2(4000),
    pPOLICY2 VARCHAR2(4000),
    pSTOCK NUMBER(7) NOT NULL,
    pDATE DATE DEFAULT SYSDATE,
    pHIT NUMBER(7) DEFAULT 0
);

CREATE SEQUENCE PRODUCT_SEQ MAXVALUE 9999999 NOCYCLE NOCACHE;

CREATE TABLE QNA_BOARD(
    qID NUMBER(7) PRIMARY KEY,
    qCATEGORY VARCHAR2(50) NOT NULL,
    mID VARCHAR2(50) REFERENCES MEMBER(mID),
    aID VARCHAR2(50) REFERENCES ADMIN(aID),
    qPW VARCHAR2(50) NOT NULL,
    qTITLE VARCHAR2(250) NOT NULL,
    qCONTENT VARCHAR2(4000) NOT NULL,
    qFILE1 VARCHAR2(250),
    qFILE2 VARCHAR2(250),
    qDATE DATE DEFAULT SYSDATE,
    qHIT NUMBER(7) DEFAULT 0,
    qGROUP NUMBER(7) NOT NULL,
    qSTEP NUMBER(7) NOT NULL,
    qINDENT NUMBER(7) NOT NULL,
    qIP VARCHAR2(50) NOT NULL
);

CREATE SEQUENCE QNA_SEQ MAXVALUE 9999999 NOCYCLE NOCACHE;

CREATE TABLE CART(
    cID NUMBER(7) PRIMARY KEY,
    mID VARCHAR2(50) REFERENCES MEMBER(mID) NOT NULL,
    pID NUMBER(7) REFERENCES PRODUCT(pID) UNIQUE,
    cAmount NUMBER(7) DEFAULT 0,
    cDATE DATE DEFAULT SYSDATE
);

CREATE SEQUENCE CART_SEQ MAXVALUE 9999999 NOCYCLE NOCACHE;

CREATE TABLE ORDERS(
    oID NUMBER(7) PRIMARY KEY,
    oDATE DATE DEFAULT SYSDATE,
    mID VARCHAR2(50) REFERENCES MEMBER(mID) NOT NULL,
    oNAME VARCHAR2(50) NOT NULL,
    oPHONE VARCHAR2(50) NOT NULL,
    oADDRESS VARCHAR2(350) NOT NULL,
    oPAYMENT VARCHAR2(50) NOT NULL,
    oINVOICE NUMBER(30)
);

CREATE SEQUENCE ORDERS_SEQ MAXVALUE 9999999 NOCYCLE NOCACHE;

CREATE TABLE ORDERS_DETAIL(
    odID NUMBER(7) PRIMARY KEY,
    oID NUMBER(7) NOT NULL,
    pID NUMBER(7) REFERENCES PRODUCT(pID) NOT NULL,
    odAMOUNT NUMBER(7) DEFAULT 0
);

CREATE SEQUENCE ORDERS_DETAIL_SEQ MAXVALUE 9999999 NOCYCLE NOCACHE;

CREATE TABLE REVIEW_BOARD(
    rID NUMBER(7) PRIMARY KEY,
    oID NUMBER(7) REFERENCES ORDERS(oID) NOT NULL,
    pID NUMBER(7) REFERENCES PRODUCT(pID) NOT NULL,
    mID VARCHAR2(50) REFERENCES MEMBER(mID),
    aID VARCHAR2(50) REFERENCES ADMIN(aID),
    rPW VARCHAR2(50),
    rTITLE VARCHAR2(250) NOT NULL,
    rCONTENT VARCHAR2(4000) NOT NULL,
    rFILE1 VARCHAR2(250),
    rFILE2 VARCHAR2(250),
    rDATE DATE DEFAULT SYSDATE,
    rHIT NUMBER(7) DEFAULT 0,
    rGROUP NUMBER(7) NOT NULL,
    rSTEP NUMBER(7) NOT NULL,
    rINDENT NUMBER(7) NOT NULL,
    rIP VARCHAR2(50) NOT NULL
);

CREATE SEQUENCE REVIEW_SEQ MAXVALUE 9999999 NOCYCLE NOCACHE;

CREATE TABLE WISHLIST(
    wID NUMBER(7) PRIMARY KEY,
    wDATE DATE DEFAULT SYSDATE NOT NULL,
    pID NUMBER(7) REFERENCES PRODUCT(pID) UNIQUE NOT NULL,
    mID VARCHAR2(50) REFERENCES MEMBER(mID)
);

CREATE SEQUENCE WISHLIST_SEQ MAXVALUE 9999999 NOCYCLE NOCACHE;

COMMIT;


