-- MEMBER
SELECT*FROM MEMBER;
CREATE SEQUENCE JOIN_SEQ MAXVALUE 9999 NOCYCLE NOCACHE;

INSERT INTO MEMBER(mID,mPW,mNAME,mEMAIL,mPHONE,mADDRESS,mBIRTH)
    VALUES ('aaa','111','박지영','aaa@aaa.aaa','01050910108','서울시','1990/01/08');
INSERT INTO MEMBER(mID,mPW,mNAME,mEMAIL,mPHONE,mADDRESS,mBIRTH)
    VALUES ('aaa'||JOIN_SEQ.NEXTVAL,'111','박지영','aaa@aaa.aaa','01050910108','서울시','1990/01/08');
INSERT INTO MEMBER(mID,mPW,mNAME,mEMAIL,mPHONE,mADDRESS,mBIRTH)
    VALUES ('aaa'||JOIN_SEQ.NEXTVAL,'111','박지영','aaa@aaa.aaa','01050910108','서울시','1990/01/08');
INSERT INTO MEMBER(mID,mPW,mNAME,mEMAIL,mPHONE,mADDRESS,mBIRTH)
    VALUES ('aaa'||JOIN_SEQ.NEXTVAL,'111','박지영','aaa@aaa.aaa','01050910108','서울시','1990/01/08');
INSERT INTO MEMBER(mID,mPW,mNAME,mEMAIL,mPHONE,mADDRESS,mBIRTH)
    VALUES ('aaa'||JOIN_SEQ.NEXTVAL,'111','박지영','aaa@aaa.aaa','01050910108','서울시','1990/01/08');

COMMIT;

-- ADMIN
SELECT*FROM ADMIN;
INSERT INTO ADMIN (aID, aPW) VALUES ('admin','111');

COMMIT;

-- QNA_BOARD
INSERT INTO qCATEGORY (qCATEGORY) VALUES ('상품문의');
INSERT INTO qCATEGORY (qCATEGORY) VALUES ('배송문의');
INSERT INTO qCATEGORY (qCATEGORY) VALUES ('기타문의');
INSERT INTO qCATEGORY (qCATEGORY) VALUES ('문의답변');
SELECT*FROM qCATEGORY;

COMMIT;

DELETE QNA_BOARD;

INSERT INTO QNA_BOARD (qID, qCATEGORY, mID, aID, qPW, pID, qTITLE, qCONTENT, qFILE1, qFILE2, qGROUP, qSTEP, qINDENT, qIP)
    VALUES (QNA_SEQ.NEXTVAL, '상품문의', 'aaa', NULL, '111', 1, '제목', '내용', NULL, NULL, QNA_SEQ.CURRVAL, 0, 0, '111.111.11.11');
INSERT INTO QNA_BOARD (qID, qCATEGORY, mID, aID, qPW, pID, qTITLE, qCONTENT, qFILE1, qFILE2, qGROUP, qSTEP, qINDENT, qIP)
    VALUES (QNA_SEQ.NEXTVAL, '상품문의', 'aaa', NULL, '111', 2, '제목', '내용', NULL, NULL, QNA_SEQ.CURRVAL, 0, 0, '111.111.11.11');
INSERT INTO QNA_BOARD (qID, qCATEGORY, mID, aID, qPW, pID, qTITLE, qCONTENT, qFILE1, qFILE2, qGROUP, qSTEP, qINDENT, qIP)
    VALUES (QNA_SEQ.NEXTVAL, '상품문의', 'aaa', NULL, '111', 3, '제목', '내용', NULL, NULL, QNA_SEQ.CURRVAL, 0, 0, '111.111.11.11');
INSERT INTO QNA_BOARD (qID, qCATEGORY, mID, aID, qPW, pID, qTITLE, qCONTENT, qFILE1, qFILE2, qGROUP, qSTEP, qINDENT, qIP)
    VALUES (QNA_SEQ.NEXTVAL, '상품문의', 'aaa', NULL, '111', 4, '제목', '내용', NULL, NULL, QNA_SEQ.CURRVAL, 0, 0, '111.111.11.11');
INSERT INTO QNA_BOARD (qID, qCATEGORY, mID, aID, qPW, pID, qTITLE, qCONTENT, qFILE1, qFILE2, qGROUP, qSTEP, qINDENT, qIP)
    VALUES (QNA_SEQ.NEXTVAL, '상품문의', 'aaa', NULL, '111', 5, '제목', '내용', NULL, NULL, QNA_SEQ.CURRVAL, 0, 0, '111.111.11.11');
INSERT INTO QNA_BOARD (qID, qCATEGORY, mID, aID, qPW, pID, qTITLE, qCONTENT, qFILE1, qFILE2, qGROUP, qSTEP, qINDENT, qIP)
    VALUES (QNA_SEQ.NEXTVAL, '상품문의', 'aaa', NULL, '111', 6, '제목', '내용', NULL, NULL, QNA_SEQ.CURRVAL, 0, 0, '111.111.11.11');

-- PRODUCT
-- pCATEGORY
--SELECT*FROM pCATEGORY;
SELECT*FROM PRODUCT;
--INSERT INTO pCATEGORY (pCATEGORY1, pCATEGORY2) VALUES ('FURNITURE', '');

INSERT INTO PRODUCT (pID, pCATEGORY, pNAME, pPRICE, pDISCOUNT, 
    pIMAGE1, pIMAGE2, pCONTENT, pPOLICY1, pPOLICY2, pSTOCK)
    VALUES (PRODUCT_SEQ.NEXTVAL, 'FURNITURE', 'SAMPLE PRODUCT', PRODUCT_SEQ.CURRVAL||90000, 0, 'sample'||PRODUCT_SEQ.CURRVAL||'.jpg',
        NULL, 'THIS IS A SAMPLE PRODUCT', '교환환불 규정입니다.', '배송규정입니다.',
        10);
        
COMMIT;       
        
-- REVIEW BOARD
INSERT INTO REVIEW_BOARD (rID, oID, pID, mID, aID, rPW, rTITLE, rCONTENT, rFILE1, rFILE2, rGROUP, rSTEP, rINDENT, rIP)
    VALUES (REVIEW_SEQ.NEXTVAL, '2', '1', 'aaa', NULL, '111', '리뷰제목', '리뷰내용', '리뷰첨부파일', NULL, REVIEW_SEQ.CURRVAL, 0, 0, '111.111.11.11');
INSERT INTO REVIEW_BOARD (rID, oID, pID, mID, aID, rPW, rTITLE, rCONTENT, rFILE1, rFILE2, rGROUP, rSTEP, rINDENT, rIP)
    VALUES (REVIEW_SEQ.NEXTVAL, '4', '1', 'aaa', NULL, '111', '리뷰제목', '리뷰내용', '리뷰첨부파일', NULL, REVIEW_SEQ.CURRVAL, 0, 0, '111.111.11.11');
INSERT INTO REVIEW_BOARD (rID, oID, pID, mID, aID, rPW, rTITLE, rCONTENT, rFILE1, rFILE2, rGROUP, rSTEP, rINDENT, rIP)
    VALUES (REVIEW_SEQ.NEXTVAL, '5', '1', 'aaa', NULL, '111', '리뷰제목', '리뷰내용', '리뷰첨부파일', NULL, REVIEW_SEQ.CURRVAL, 0, 0, '111.111.11.11');
INSERT INTO REVIEW_BOARD (rID, oID, pID, mID, aID, rPW, rTITLE, rCONTENT, rFILE1, rFILE2, rGROUP, rSTEP, rINDENT, rIP)
    VALUES (REVIEW_SEQ.NEXTVAL, '6', '1', 'aaa', NULL, '111', '리뷰제목', '리뷰내용', '리뷰첨부파일', NULL, REVIEW_SEQ.CURRVAL, 0, 0, '111.111.11.11');
INSERT INTO REVIEW_BOARD (rID, oID, pID, mID, aID, rPW, rTITLE, rCONTENT, rFILE1, rFILE2, rGROUP, rSTEP, rINDENT, rIP)
    VALUES (REVIEW_SEQ.NEXTVAL, '7', '1', 'aaa', NULL, '111', '리뷰제목', '리뷰내용', '리뷰첨부파일', NULL, REVIEW_SEQ.CURRVAL, 0, 0, '111.111.11.11');
INSERT INTO REVIEW_BOARD (rID, oID, pID, mID, aID, rPW, rTITLE, rCONTENT, rFILE1, rFILE2, rGROUP, rSTEP, rINDENT, rIP)
    VALUES (REVIEW_SEQ.NEXTVAL, '8', '1', 'aaa', NULL, '111', '리뷰제목', '리뷰내용', '리뷰첨부파일', NULL, REVIEW_SEQ.CURRVAL, 0, 0, '111.111.11.11');
    

-- ORDERS
INSERT INTO ORDERS (oID, mID, oNAME, oPHONE, oADDRESS, oPAYMENT, oINVOICE)
    VALUES (ORDERS_SEQ.NEXTVAL, 'aaa', '받는사람', '010-1111-1111', '서울시', '무통장입금', NULL);
SELECT*FROM ORDERS;    

COMMIT;
